version: '3.8'

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/weather-app
      - /weather-app/node_modules
    command: npm run dev






